# Generated by Django 2.1.7 on 2019-05-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='aims',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposal',
            field=models.TextField(null=True),
        ),
    ]
